# Generated by Django 2.2.4 on 2019-11-13 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reading_count', '0007_auto_20191113_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
